README updates
RAIVNLab/MRL pull request #4
Opened 2022-06-27 16:47 UTC by aniketrege

2022-06-27 19:35 UTC, adityakusupati commented on README.md
> +This repository contains code to train, evaluate, and analyze Matryoshka Representations with a ResNet-50 backbone. The training pipeline utilizes efficient [FFCV](https://github.com/libffcv/ffcv-ima
ResNet50

2022-06-27 19:38 UTC, adityakusupati commented on README.md
> +In the paper we only consider $rep size \in  [8, 16, 32, 64, 128, 256, 512, 1024, 2048]$. To evaluate on other rep. sizes, change the variable `NESTING_LIST` in `pytorch_eval.py`.
You can add accuracy plots from the paper if that makes it more convincing.

2022-06-30 22:37 UTC, bhattg requested changes
Hi Aniket, I've made changes on the main branch regarding the model analysis folder. You need to be careful while merging. Other than that, this is good to go.

2022-06-30 22:37 UTC, bhattg commented on README.md
>  ## Retrieval Performance
This should be ##[Retrieval Performance](retrieval/)

2022-06-30 22:37 UTC, bhattg commented on model_analysis/README.md
> +**TODO @ GB** please add a comment why and how it is different from paper
I've taken care of this in the main branch. There will be a slight merge conflict since I changed the GradCAM.ipynb and README.md.

2022-06-30 22:37 UTC, bhattg commented on model_analysis/README.md
> +**TODO @ GB:** add WordNet link?
Added the nltk link to wordnet.

2022-07-02 01:12 UTC, merged